using System.Collections.Immutable;

namespace CodeChops.DomainDrivenDesign.DomainModeling.SourceGeneration;

[Generator]
public class SourceBuilder : IIncrementalGenerator
{
	internal const string AttributeNamespace		= "CodeChops.DomainDrivenDesign.DomainModeling.Attributes";
	internal const string AttributeName				= "GenerateStronglyTypedId";
	internal const string EntityNamespace			= "CodeChops.DomainDrivenDesign.DomainModeling";
	internal const string EntityName				= "Entity";
	internal const string IdNamespace				= "CodeChops.DomainDrivenDesign.DomainModeling.Identities";
	internal const string DefaultIdTypeName			= "Identity";
	internal const string DefaultIdPropertyName		= "Id";
	internal const string DefaultIdPrimitiveType	= "UInt64";
	
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{		
		var valueProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: SyntaxReceiver.CheckIfProbablyNeedsStronglyTypedId,
				transform: static (context, _) => SyntaxReceiver.GetModel((TypeDeclarationSyntax)context.Node, context.SemanticModel))
			.Where(static model => model is not null)
			.Collect();
		
		context.RegisterSourceOutput(source: valueProvider, action: CreateSource!);
	}
	
	private static void CreateSource(SourceProductionContext context, ImmutableArray<DataModel> models)
	{
		foreach (var model in models)
		{
			var code = CreateSource(model);

			var fileName = model.Namespace is null 
				? model.OuterClassName 
				: $"{model.Namespace}.{model.OuterClassName}";
			
			context.AddSource($"{fileName}.{model.IdTypeName}.g.cs", SourceText.From(code, Encoding.UTF8));
		}
	}

	private static string CreateSource(DataModel data)
	{
		var className = $"{data.OuterClassName}{data.OuterClassGenericTypeParameters}";

		var code = $@"// <auto-generated />
#nullable enable
using System;
using CodeChops.DomainDrivenDesign.DomainModeling.Identities;

{GetNamespaceDeclaration()}

{GetClassDeclaration()}
{{	
	{GetIdPropertyCreation()}
	{GetIdObjectCreation(data.GenerationMethod, data.IdTypeName, data.IdBaseType, data.IdPrimitiveType)}
	{GetEqualityComparison()}
}}

#nullable restore
";

		return code;
		
		// Creates the namespace definition of the location of the enum definition (or null if the namespace is not defined).
		string? GetNamespaceDeclaration()
		{
			if (data.Namespace is null) return null;

			var code = $@"namespace {data.Namespace};";
			return code;
		}

		string GetClassDeclaration()
		{
			var iHasIdImplementation = data.GenerationMethod == GenerationMethod.EntityBase || data.IdPropertyName != DefaultIdPropertyName 
				? null
				: $" : IHasId<{className}.{data.IdTypeName}>";
			
			var code = $"{data.OuterClassDeclaration} {className}{iHasIdImplementation}";
			return code;
		}
		
		string GetIdPropertyCreation()
		{
			if (data.GenerationMethod == GenerationMethod.EntityBase)
			{
				return @$"
	public abstract Id {data.IdPropertyName} {{ get; }}
";
			}

			var code = $@"
	public {(data.GenerationMethod == GenerationMethod.EntityImplementation ? "override " : "")}{data.IdTypeName} {data.IdPropertyName} {{ get; }} = new();
";

			return code;
		}

		string GetEqualityComparison()
		{
			if (data.GenerationMethod is GenerationMethod.EntityImplementation or GenerationMethod.Record)
				return "";
					
			var code = @$"
	public sealed override int GetHashCode()
	{{
		return this.Id.HasDefaultValue
			? HashCode.Combine(this)
			: this.Id.GetHashCode();
	}}
	
	public sealed override bool Equals(object? obj)
	{{
		return obj is {className} other 
		       && obj.GetType() == this.GetType() 
		       && this.Equals(other);
	}}

	public bool Equals({className}? other)
	{{
		if (other is null) return false;
		if (ReferenceEquals(this, other)) return true;
		if (other.GetType() != this.GetType()) return false;
		
		return !this.Id.HasDefaultValue && this.Id.Equals(other.Id);
	}}";

			return code;
		}
		
		static string? GetIdObjectCreation(GenerationMethod generationMethod, string idName, string idBaseType, string? idPrimitiveType)
		{
			if (generationMethod == GenerationMethod.EntityBase)
				return null;
			
			var code = $@"
	public partial record {idName} : {idBaseType}
	{{ 
		public {idName}({idPrimitiveType} value) : base(value) {{ }}
		public {idName}() : base() {{ }}
	}}
";

			return code;
		}
	}
}
