namespace CodeChops.DomainDrivenDesign.DomainModeling.SourceGeneration.GlobalUsingsGenerator;

[Generator]
public class GlobalUsingsGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(i =>
		{
			const string globalUsingsCode = @"// <auto-generated />
global using CodeChops.DomainDrivenDesign.DomainModeling.Attributes;
global using CodeChops.DomainDrivenDesign.DomainModeling.Attributes.ValueObjects;
global using CodeChops.DomainDrivenDesign.DomainModeling.Collections;
global using CodeChops.DomainDrivenDesign.DomainModeling.Exceptions;
global using CodeChops.DomainDrivenDesign.DomainModeling.Exceptions.System;
global using CodeChops.DomainDrivenDesign.DomainModeling.Exceptions.Validation;
global using CodeChops.DomainDrivenDesign.DomainModeling.Extensions;
global using CodeChops.DomainDrivenDesign.DomainModeling.Factories;
global using CodeChops.DomainDrivenDesign.DomainModeling.Identities;
global using CodeChops.DomainDrivenDesign.DomainModeling.Validation;
global using CodeChops.DomainDrivenDesign.DomainModeling.Validation.Guards;
global using CodeChops.DomainDrivenDesign.DomainModeling;
global using CodeChops.GenericMath;
";

			i.AddSource("GlobalUsings.g.cs", globalUsingsCode);
		});
	}
}
