using System.Collections.Immutable;
using CodeChops.SourceGeneration.Utilities;
using Microsoft.CodeAnalysis.Diagnostics;

namespace CodeChops.DomainDrivenDesign.DomainModeling.SourceGeneration.IdentityGenerator;

[Generator]
public class IdGenerator : IIncrementalGenerator
{
	internal const string AttributeNamespace		= "CodeChops.DomainDrivenDesign.DomainModeling.Attributes";
	internal const string AttributeName				= "GenerateStronglyTypedId";
	internal const string EntityNamespace			= "CodeChops.DomainDrivenDesign.DomainModeling";
	internal const string EntityName				= "Entity";
	internal const string IdNamespace				= "CodeChops.DomainDrivenDesign.DomainModeling.Identities";
	internal const string DefaultIdTypeName			= "Identity";
	internal const string DefaultIdPropertyName		= "Id";
	internal const string DefaultIdPrimitiveType	= "UInt64";
	
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{		
		var valueProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				predicate: IdSyntaxReceiver.CheckIfProbablyNeedsStronglyTypedId,
				transform: static (context, _) => IdSyntaxReceiver.GetModel((TypeDeclarationSyntax)context.Node, context.SemanticModel))
			.Where(static model => model is not null)
			.Collect()
			.Combine(context.AnalyzerConfigOptionsProvider);
		
		context.RegisterSourceOutput(source: valueProvider, action: static (context, valueProvider) => CreateSource(context, valueProvider.Left!, valueProvider.Right));
	}
	
	private static void CreateSource(SourceProductionContext context, ImmutableArray<IdDataModel> models, AnalyzerConfigOptionsProvider configOptionsProvider)
	{
		foreach (var model in models)
		{
			var code = CreateSource(model);

			var fileName = model.Namespace is null 
				? model.OuterClassName 
				: $"{model.Namespace}.{model.OuterClassName}";

			fileName = $"{fileName}.{model.IdTypeName}";
			fileName = FileNameHelpers.GetFileName(fileName, configOptionsProvider);
			
			context.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
		}
	}

	private static string CreateSource(IdDataModel data)
	{
		var className = $"{data.OuterClassName}{data.OuterClassGenericTypeParameters}";

		var code = $@"// <auto-generated />
#nullable enable
using System;
using CodeChops.DomainDrivenDesign.DomainModeling.Identities;
{GetPrimitiveTypeUsing()}

{GetNamespaceDeclaration()}

{GetClassDeclaration()}
{{	
	{GetIdPropertyCreation()}
	{GetIdObjectCreation(data.IdGenerationMethod, data.IdTypeName, data.IdBaseType, data.IdPrimitiveType)}
	{GetEqualityComparison()}
}}

#nullable restore
";

		return code;


		string? GetPrimitiveTypeUsing()
		{
			return data.PrimitiveTypeNamespace is null 
				? null
				: $"using {data.PrimitiveTypeNamespace};";
		}
		
		
		// Creates the namespace definition of the location of the enum definition (or null if the namespace is not defined).
		string? GetNamespaceDeclaration()
		{
			if (data.Namespace is null) return null;

			var code = $@"namespace {data.Namespace};";
			return code;
		}

		
		string GetClassDeclaration()
		{
			var iHasIdImplementation = data.IdGenerationMethod == IdGenerationMethod.EntityBase || data.IdPropertyName != DefaultIdPropertyName 
				? null
				: $" : IHasId<{className}.{data.IdTypeName}>";
			
			var code = $"{data.OuterClassDeclaration} {className}{iHasIdImplementation}";
			return code;
		}
		
		
		string GetIdPropertyCreation()
		{
			if (data.IdGenerationMethod == IdGenerationMethod.EntityBase)
			{
				return @$"
	public abstract Id {data.IdPropertyName} {{ get; }}
";
			}

			var code = $@"
	public {(data.IdGenerationMethod == IdGenerationMethod.EntityImplementation ? "override " : "")}{data.IdTypeName} {data.IdPropertyName} {{ get; }} = new();
";

			return code;
		}

		
		string GetEqualityComparison()
		{
			if (data.IdGenerationMethod is IdGenerationMethod.EntityImplementation)
				return "";
					
			var code = @$"
	public sealed override int GetHashCode()
	{{
		return this.Id.HasDefaultValue
			? HashCode.Combine(this)
			: this.Id.GetHashCode();
	}}
	
	public sealed override bool Equals(object? obj)
	{{
		return obj is {className} other 
		       && obj.GetType() == this.GetType() 
		       && this.Equals(other);
	}}

	public bool Equals({className}? other)
	{{
		if (other is null) return false;
		if (ReferenceEquals(this, other)) return true;
		if (other.GetType() != this.GetType()) return false;
		
		return !this.Id.HasDefaultValue && this.Id.Equals(other.Id);
	}}

	public static bool operator ==({className}? left, {className}? right)
	{{
		if (left is null && right is null) return true;
		if (left is null || right is null) return false;
		return left.Equals(right);
	}}
	
	public static bool operator !=({className}? left, {className}? right) 
		=> !(left == right);
";

			return code;
		}
		
		
		static string? GetIdObjectCreation(IdGenerationMethod generationMethod, string idName, string idBaseType, string? idPrimitiveType)
		{
			if (generationMethod == IdGenerationMethod.EntityBase)
				return null;
			
			var code = $@"
	public partial record {idName} : {idBaseType}
	{{ 
		public {idName}({idPrimitiveType} value) : base(value) {{ }}
		public {idName}() : base() {{ }}
	}}
";

			return code;
		}
	}
}
